### ISSUE TITLE
Conflict with "view any unpublished content" permission

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/content_view_access#2]
I have a simple site that uses this module and in troubleshooting why an "Editor" role (which is granted permission to "view any unpublished content") is not allowing users to see unpublished content in the Content overview page, it seems to come down to this module. If I disable the module, they can see the unpublished content and if I re-enable it, they can't. I haven't tracked it further than that yet.

**Comment by laryn** [comment]
@herbdool  I submitted a PR on a new branch which will need to be tested further but seems to be working in my environment with the "view any unpublished content" permission.

**Comment by herbdool** [comment]
Thanks @laryn. I'm going to take a look and test to see if this is what we want. The hook runs when a node is saved and creates a node access grant table, so it is a bit harder to wrap my head around it. It would be easier if it called it each time the node was viewed.https://api.backdropcms.org/api/backdrop/core%21modules%21node%21node.api.php/function/hook_node_access_records/1

**Comment by herbdool** [comment]
I think the solution is in D8 version of node_view_permissions. https://cgit.drupalcode.org/node_view_permissions/tree/node_view_permissions.module. It creates separate access realms for the unpublished permissions.

**Comment by herbdool** [comment]
@laryn I've adapted your branch to use the approach used in the d8 version. Thanks for your help!

**Comment by laryn** [comment]
@herbdool Sounds great! I'll test later this week but looks good at a glance.
